
package com.blw.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestWebServiceImplService", targetNamespace = "http://webservice.test.blw.com/", wsdlLocation = "${webservice.address}/webservice?wsdl")
public class TestWebServiceImplService
    extends Service
{

    private final static URL TESTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TESTWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.test.blw.com/", "TestWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("${webservice.address}/webservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TESTWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TestWebServiceImplService() {
        super(__getWsdlLocation(), TESTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public TestWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public TestWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TESTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public TestWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public TestWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServiceImplPort")
    public TestWebService getTestWebServiceImplPort() {
        return super.getPort(new QName("http://webservice.test.blw.com/", "TestWebServiceImplPort"), TestWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServiceImplPort")
    public TestWebService getTestWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.test.blw.com/", "TestWebServiceImplPort"), TestWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TESTWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TESTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
